### ISSUE TITLE
Cannot login into Paypal

### ISSUE THREAD

**Issue by VamshiKyra** [zeddz92/react-native-paypal#1]
I have installed the library as per instructions. Trying to login into Paypal but it is not letting me to login.

This is the code I am using:

RNPaypal.paymentRequest({
    clientId: '<YOUR CLIENT ID>',
    environment: RNPaypal.ENVIRONMENT.SANDBOX,
    intent: RNPaypal.INTENT.SALE,
    price: 60,
    currency: 'USD',
    description: `Android testing`,
    acceptCreditCards: true
}).then(response => {
    console.log(response)
}).catch(err => {
    console.log(err.message)
})

Environment: iOS 12.0.1

**Comment by lopezredd** [comment]
Hey @VamshiKyra you have to specify your clientId and use a sandbox credential related to that clientId account at [https://developer.paypal.com/developer/accounts/](url)

**Comment by VamshiKyra** [comment]
@lopezredd  I have specified clientId. I created REST API App and used the client ID. Do I have to specify anything else?

**Comment by lopezredd** [comment]
@VamshiKyra if you use the sandbox environment you'll only login with sanbox accounts you make. You could also use NO_NETWORK and avoid creating sandbox accounts.

[https://developer.paypal.com/developer/accounts/create](url) here you create the sandobox account to work with your client id.

**Comment by VamshiKyra** [comment]
@lopezredd 
I tried NO_NETWORK, it works fine. 

I am using exact same account which I used to create Paypal developer account. Even though I am not able to login SANDBOX environment.

![img_4a04ad0cd2d6-1](https://user-images.githubusercontent.com/40666762/48284480-8886d880-e42d-11e8-8453-04cd8a53e776.jpeg)

"Pay with Card" is crashing the app. Can I hide the option? or Can I make it work?

**Comment by lopezredd** [comment]
You can't use your paypal developer account credentials for that, you need to go to your dashboard and create a sandbox account.

You can hide it setting acceptCreditCards to false

![image](https://user-images.githubusercontent.com/26311875/48284847-1ca96d80-e437-11e8-8e18-3eb5046438a9.png)

![image](https://user-images.githubusercontent.com/26311875/48284903-537f8380-e437-11e8-979e-c2e68ff13730.png)

**Comment by VamshiKyra** [comment]
@lopezredd Thanks a lot. It worked. 

Can I remove "pay with card" option? or Can I make it work?

**Comment by ghost** [comment]
@VamshiKyra did pay with CC work for you?

**Comment by eramudeep** [comment]
### Getting below error on Ios Android is working like a charm 
### **My code is**

` return await RNPaypal.paymentRequest({
        clientId: PAYPAL_SANDBOX_KEY,
        environment: RNPaypal.ENVIRONMENT.NO_NETWORK,
        intent: RNPaypal.INTENT.SALE,
        price: price,
        currency: 'USD',
        description: `Description`,
        acceptCreditCards: true
    })`
    
 I tried all possible way:
  1.  RNPaypal.ENVIRONMENT.NO_NETWORK
  2. RNPaypal.ENVIRONMENT. SANDBOX
  3. RNPaypal.ENVIRONMENT. PRODUCTION
  
  **Also changed the keys according to the environment** 
  
    _Need help asap_ 

<img width="385" alt="Screenshot 2021-01-07 at 1 16 06 PM" src="https://user-images.githubusercontent.com/38516686/103865652-880c2a00-50ea-11eb-952b-afd29db9280d.png">
