### ISSUE TITLE
Android installation issue

### ISSUE THREAD

**Issue by VamshiKyra** [zeddz92/react-native-paypal#2]
Hi,

I am trying to make Paypal work in Android. When I run "react-native run-android" this is the error. I am facing. I have created my project using react-native init myApp. I do not know how to solve this. Please help. Thanks in advance.

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find host.exp.exponent:expoview:27.0.0.
  Searched in the following locations:
      file:/Users/kyrasolutions/Library/Android/sdk/extras/m2repository/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.pom
      file:/Users/kyrasolutions/Library/Android/sdk/extras/m2repository/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.aar
      file:/Users/kyrasolutions/Library/Android/sdk/extras/google/m2repository/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.pom
      file:/Users/kyrasolutions/Library/Android/sdk/extras/google/m2repository/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.aar
      file:/Users/kyrasolutions/Library/Android/sdk/extras/android/m2repository/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.pom
      file:/Users/kyrasolutions/Library/Android/sdk/extras/android/m2repository/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.aar
      file:/Users/kyrasolutions/.m2/repository/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.pom
      file:/Users/kyrasolutions/.m2/repository/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.aar
      https://maven.google.com/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.pom
      https://maven.google.com/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.aar
      https://dl.google.com/dl/android/maven2/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.pom
      https://dl.google.com/dl/android/maven2/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.aar
      https://jcenter.bintray.com/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.pom
      https://jcenter.bintray.com/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.aar
      file:/Users/kyrasolutions/Documents/ExploreFlorida4/node_modules/react-native/android/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.pom
      file:/Users/kyrasolutions/Documents/ExploreFlorida4/node_modules/react-native/android/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.aar
      file:/Users/kyrasolutions/Documents/ExploreFlorida4/node_modules/react-native-background-geolocation/android/libs/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.pom
      file:/Users/kyrasolutions/Documents/ExploreFlorida4/node_modules/react-native-background-geolocation/android/libs/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.aar
      file:/Users/kyrasolutions/Documents/ExploreFlorida4/node_modules/react-native-background-fetch/android/libs/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.pom
      file:/Users/kyrasolutions/Documents/ExploreFlorida4/node_modules/react-native-background-fetch/android/libs/host/exp/exponent/expoview/27.0.0/expoview-27.0.0.aar
  Required by:
      project :app > project :react-native-paypal-lib

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
1 actionable task: 1 executed
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by lopezredd** [comment]
Yep, there's a problem with the dependencies on android, expoview should not be there. Can you upgrade to version 1.0.5? `npm i react-native-paypal-lib@latest`

**Comment by ghost** [comment]
+1 upgraded to the latest, still getting the same issue.

RN : 0.56

`> Task :react-native-paypal-lib:compileDebugJavaWithJavac FAILED
/Users/crushy/edapt/node_modules/react-native-paypal-lib/android/src/main/java/com/reactlibrary/RNPaypalModule.java:11: error: package com.facebook.internal does not exist
import com.facebook.internal.BundleJSONConverter;
                            ^
/Users/crushy/edapt/node_modules/react-native-paypal-lib/android/src/main/java/com/reactlibrary/RNPaypalModule.java:33: error: package host.exp.expoview does not exist
import host.exp.expoview.Exponent;
                        ^
/Users/crushy/edapt/node_modules/react-native-paypal-lib/android/src/main/java/com/reactlibrary/RNPaypalModule.java:48: error: package host.exp.exponent does not exist
  private final host.exp.exponent.ActivityResultListener mActivityEventListener = new host.exp.exponent.ActivityResultListener() {
                                 ^
/Users/crushy/edapt/node_modules/react-native-paypal-lib/android/src/main/java/com/reactlibrary/RNPaypalModule.java:48: error: package host.exp.exponent does not exist
  private final host.exp.exponent.ActivityResultListener mActivityEventListener = new host.exp.exponent.ActivityResultListener() {
                                                                                                       ^
/Users/crushy/edapt/node_modules/react-native-paypal-lib/android/src/main/java/com/reactlibrary/RNPaypalModule.java:61: error: cannot find symbol
    Exponent.getInstance().addActivityResultListener(mActivityEventListener);
    ^
  symbol:   variable Exponent
  location: class RNPaypalModule
/Users/crushy/edapt/node_modules/react-native-paypal-lib/android/src/main/java/com/reactlibrary/RNPaypalModule.java:150: error: cannot find symbol
          Bundle bundle = BundleJSONConverter.convertToBundle(confirm.toJSONObject());
                          ^
  symbol:   variable BundleJSONConverter
  location: class RNPaypalModule
6 errors`

**Comment by VamshiKyra** [comment]
RNPaypalModule.java:11: error: package com.facebook.internal does not exist
import com.facebook.internal.BundleJSONConverter;

RNPaypalModule.java:33: error: package host.exp.expoview does not exist
import host.exp.expoview.Exponent;

RNPaypalModule.java:48: error: package host.exp.exponent does not exist
  private final host.exp.exponent.ActivityResultListener mActivityEventListener = new host.exp.exponent.ActivityResultListener() {

RNPaypalModule.java:48: error: package host.exp.exponent does not exist
  private final host.exp.exponent.ActivityResultListener mActivityEventListener = new host.exp.exponent.ActivityResultListener() {

RNPaypalModule.java:61: error: cannot find symbol
    Exponent.getInstance().addActivityResultListener(mActivityEventListener);
  symbol:   variable Exponent
  location: class RNPaypalModule
RNPaypalModule.java:150: error: cannot find symbol
          Bundle bundle = BundleJSONConverter.convertToBundle(confirm.toJSONObject());

  symbol:   variable BundleJSONConverter
  location: class RNPaypalModule
6 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-paypal-lib:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

These are errors I got. Please help in resolving these.

Thansk!

**Comment by lopezredd** [comment]
@VamshiKyra are you using expo?

**Comment by VamshiKyra** [comment]
No. I am using react native cli. Created application using react-native init myApp

**Comment by lopezredd** [comment]
can you share me your app.json?

**Comment by VamshiKyra** [comment]
{
  "name": "ExploreFlorida",
  "displayName": "Explore Florida"
}

**Comment by VamshiKyra** [comment]
Do you mean package.json?

**Comment by lopezredd** [comment]
yes please

**Comment by VamshiKyra** [comment]
{
  "name": "ExploreFlorida",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@types/react": "16.4.14",
    "axios": "^0.18.0",
    "geolib": "^2.0.24",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "react": "16.5.0",
    "react-native": "^0.57.1",
    "react-native-background-geolocation": "^2.14.1",
    "react-native-calendario": "^0.2.4",
    "react-native-elements": "^0.19.1",
    "react-native-fbsdk": "0.8.0",
    "react-native-firebase": "5.0.0",
    "react-native-geojson": "^0.1.1",
    "react-native-google-places-autocomplete": "^1.3.9",
    "react-native-google-signin": "^1.0.0-rc7",
    "react-native-maps": "^0.21.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-payments": "^0.7.1",
    "react-native-paypal-lib": "^1.0.5",
    "react-native-router-flux": "^4.0.5",
    "react-native-touch-id": "^4.1.0",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "^2.14.2",
    "react-paypal-express-checkout": "^1.0.5",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0",
    "rn-sliding-up-panel": "^1.2.1",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.1.0",
    "@babel/runtime": "^7.0.0",
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "^0.47.0",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.js$": "<RELATIVE_PATH>/preprocessor.js"
    }
  }
}

**Comment by VamshiKyra** [comment]
@lopezredd Did you get a chance to look into it?

**Comment by lopezredd** [comment]
@VamshiKyra  Yes, sorry for the late response, i've been busy lately. It seems the code uses some expo code for handling activity events. That's why you get host.exp.exponent:expoview not found since expo is not present in the proyect. I removed all expo dependencies in a new branch: react-native. You can install it like this  `npm install git://github.com/zeddz92/react-native-paypal#react-native --save` 

Just in case, this is my package.json where i test it:
{
  "name": "paypalTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.1",
    "react-native": "0.57.5",
    "react-native-paypal-lib": "git://github.com/zeddz92/react-native-paypal.git#react-native"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.2",
    "react-test-renderer": "16.6.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by VamshiKyra** [comment]
@lopezredd OMG! Thanks a lot! Really a big help. I will try new module.

**Comment by VamshiKyra** [comment]
@lopezredd I have been trying new module but I am facing an issue. After payment "then response" is not working. I think payment is not going through. Please check! Thanks in advance.

      RNPaypal.paymentRequest({
        clientId: "<MY Client ID>",
        environment: RNPaypal.ENVIRONMENT.SANDBOX,
        intent: RNPaypal.INTENT.SALE,
        price: parseFloat(newTotal),
        currency: "USD",
        description: `Total`,
        acceptCreditCards: true
      })
        .then(response =>console.log(response))
        .catch(err => {
          console.log(err.message);
        });

**Comment by VamshiKyra** [comment]
{
  "name": "ExploreFlorida",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@types/react": "16.4.14",
    "axios": "^0.18.0",
    "formik": "^1.3.2",
    "geolib": "^2.0.24",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "react": "16.5.0",
    "react-native": "^0.57.1",
    "react-native-background-geolocation": "^2.14.1",
    "react-native-calendario": "^0.2.5",
    "react-native-credit-card-input": "^0.4.1",
    "react-native-elements": "^0.19.1",
    "react-native-email": "^1.0.2",
    "react-native-fbsdk": "0.8.0",
    "react-native-firebase": "5.0.0",
    "react-native-formik": "^1.5.5",
    "react-native-geojson": "^0.1.1",
    "react-native-google-places-autocomplete": "^1.3.9",
    "react-native-google-signin": "^1.0.0-rc7",
    "react-native-maps": "^0.21.0",
    "react-native-material-textfield": "^0.12.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-passkit-wallet": "^0.1.4",
    "react-native-payments": "^0.7.1",
    "react-native-paypal-lib": "git://github.com/zeddz92/react-native-paypal#react-native",
    "react-native-qrcode": "^0.2.7",
    "react-native-router-flux": "^4.0.5",
    "react-native-touch-id": "^4.1.0",
    "react-native-vector-icons": "^5.0.0",
    "react-native-view-shot": "^2.5.0",
    "react-navigation": "^2.14.2",
    "react-redux": "^5.0.7",
    "recompose": "^0.30.0",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.10.13",
    "rn-sliding-up-panel": "^1.2.1",
    "tipsi-stripe": "^6.1.2",
    "uuid": "^3.3.2",
    "yup": "^0.26.6"
  },
  "devDependencies": {
    "@babel/core": "^7.1.0",
    "@babel/runtime": "^7.0.0",
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "^0.47.0",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.js$": "<RELATIVE_PATH>/preprocessor.js"
    }
  }
}

**Comment by VamshiKyra** [comment]
@lopezredd  Did you get a chance to look into it?

**Comment by VamshiKyra** [comment]
@lopezredd After payment "then response" is not working. I think payment is not going through. Please check! Thanks in advance.
