### ISSUE TITLE
Promise not returned from paymentRequest call, on Android

### ISSUE THREAD

**Issue by Progr1mm3r** [zeddz92/react-native-paypal#4]
**Versions**
```
"react-native-paypal-lib": "github:zeddz92/react-native-paypal#react-native",
"react": "^16.8.1",
"react-native": "^0.57.8"
```
Please note I'm using the `react-native` branch because my react-native project wouldn't build otherwise.

**Steps to reproduce**

When the following code executes: 

1. the PayPal form is displayed.
2. I enter my credentials
3. Select a payment method
4. Press "Pay Now" on the PayPal form
5. The PayPal form goes away, but the code in the `.then(response => {` block is never executed. Nor is the code in the `.catch(error => {` block.

```
import RNPaypal from 'react-native-paypal-lib';

		RNPaypal.paymentRequest({
			clientId: '<My Client Id>',
			environment: RNPaypal.ENVIRONMENT.SANDBOX,
			intent: RNPaypal.INTENT.AUTHORIZE,
			price: 30,
			currency: 'USD',
			description: 'Description',
			acceptCreditCards: false
		}).then(response => {
                        //Never executes
			console.log(response);
		}).catch(error => {
                        //Never executes
			console.log(error);
		});
```

**Comment by zeddz92** [comment]
Check now, i've made some modifications. You should update your package to version 1.0.6
github:zeddz92/react-native-paypal#react-native@1.0.6

**Comment by Progr1mm3r** [comment]
This worked, thank you!

Note that specifying the version `@1.0.6` in the URL did not work - it couldn't find `v1.0.6`. I simply did `npm update` without a version number in the URL and it pulled your changes in.
