### ISSUE TITLE
iOS Payment intent always set to 'sale'

### ISSUE THREAD

**Issue by Progr1mm3r** [zeddz92/react-native-paypal#6]
**Versions**
```
"react-native-paypal-lib": "github:zeddz92/react-native-paypal#react-native",
"react": "^16.8.1",
"react-native": "^0.57.8"
```
Please note I'm on the `react-native` branch.

**Issue**

When I create an authorization on iOS, the response I receive from `RNPaypal.paymentRequest` indicates that the payment was processed as a `sale`, not an `authorize` as desired.

Here is the response:
```
response: 
   { intent: 'sale',
     state: 'approved',
     create_time: '2019-02-19T00:14:14Z',
     id: '<PAYID>' }
```
In addition, the payment shows up in my Sandbox as an executed payment, not a pending authorization, as desired.

Here is the code:
```
import RNPaypal from 'react-native-paypal-lib';

		RNPaypal.paymentRequest({
			clientId: '<My Client Id>',
			environment: RNPaypal.ENVIRONMENT.SANDBOX,
			intent: RNPaypal.INTENT.AUTHORIZE,
			price: 30,
			currency: 'USD',
			description: 'Description',
			acceptCreditCards: false
		}).then(data => {
                        //code
		}).catch(error => {
                        //code
		});
```
It appears that the `intent` property is being ignored, and it's defaulting to `sale`.

Please note that this code works perfectly on Android.

In addition, there are differences in how the response is formatted between iOS and Android. In the promise on Android, `data.response` is a Json string and on iOS, it's a JavaScript object. I did the following as a workaround, but it isn't ideal:

```
const response = Platform.OS === 'android' ? JSON.parse(data.response) : data.response;
```

**Comment by zeddz92** [comment]
Hey @grahamyesfit android response now  return a json and intent is no longer ignored on ios.  Update your package and retry.

**Comment by Progr1mm3r** [comment]
Hey @zeddz92, excellent work. Both issues are fixed, and in very quick time. Thank you!
