### ISSUE TITLE
iOS allows credit card when acceptCreditCards is false

### ISSUE THREAD

**Issue by Progr1mm3r** [zeddz92/react-native-paypal#7]
**Versions**
```
"react-native-paypal-lib": "github:zeddz92/react-native-paypal#react-native",
"react": "^16.8.1",
"react-native": "^0.57.8"
```
Note I'm on the `react-native` branch.

**Issue**

I don't want to allow credit card entry, so I'm setting the property `acceptCreditCards: false` on the `RNPaypal.paymentRequest` call. However, when the PayPal view opens and I'm not logged in to PayPal, I'm presented with two options:
1. Pay with PayPal
2. Pay with Credit Card

Here's my code:
```
import RNPaypal from 'react-native-paypal-lib';

		RNPaypal.paymentRequest({
			clientId: '<My Client Id>',
			environment: RNPaypal.ENVIRONMENT.SANDBOX,
			intent: RNPaypal.INTENT.AUTHORIZE,
			price: 30,
			currency: 'USD',
			description: 'Description',
			acceptCreditCards: false
		}).then(data => {
                        //code
		}).catch(error => {
                        //code
		});
```

**Expected Result**

`Pay with Credit Card` should not be presented as an option. This works on Android.

**Comment by zeddz92** [comment]
Indeed, @grahamyesfit update your package and check again.
